export type BadgeRarity = 'COMMON' | 'RARE' | 'EPIC' | 'LEGENDARY';

export interface BadgeDefinition {
    key: string;
    name: string;
    emoji: string;
    description: string;
    metricType: string;
    exerciseScope: string;
    type: string;
    condition: string;
    rarity: BadgeRarity;
    category?: 'HOLISTIQUE' | 'REGULARITY' | 'PUSHUPS' | 'PULLUPS' | 'SQUATS' | 'PLANK' | 'GLOBAL';
    threshold?: number;
    seriesTarget?: number;
    isUnique?: boolean;
    isTransferable?: boolean;
    addedAt?: string;
}

export const BADGE_DEFINITIONS: BadgeDefinition[] = [
    // B1: Competitive Transferable (COMMON - Frequent Rotation)
    { key: "big_flexer", name: "Gros Flexeur", emoji: "🚀", rarity: "COMMON", category: "HOLISTIQUE", description: "Meilleur bonus reps (Total - Cible) sur une journée", metricType: "MAX_BONUS", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Obtenir le plus gros surplus de répétitions par rapport à l'objectif sur une journée." },
    { key: "regular_flexer", name: "Flexeur Régulier", emoji: "🔥", rarity: "COMMON", category: "HOLISTIQUE", description: "Plus longue streak de jours avec bonus > 0", metricType: "BONUS_STREAK", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Maintenir la plus longue série de jours consécutifs avec un surplus de répétitions." },
    { key: "perfect_soldier", name: "Le bon petit nazi", emoji: "👨🏻", rarity: "COMMON", category: "REGULARITY", description: "Celui qui fait exactement le bon nombre de reps chaque jour. Tie-break: plus longue streak.", metricType: "PERFECT_TARGET_STREAK", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Atteindre exactement l'objectif quotidien, sans une répétition de plus ni de moins." },
    { key: "king_of_set_all", name: "Roi de la Plus Longue Série", emoji: "👑", rarity: "COMMON", category: "GLOBAL", description: "Plus grande série réalisée (tous exos)", metricType: "MAX_SET", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Réaliser la plus grande série de répétitions ininterrompue, tous exercices confondus." },
    { key: "king_of_set_pushups", name: "Furie des Pompes", emoji: "💪", rarity: "COMMON", category: "PUSHUPS", description: "Plus grande série de pompes", metricType: "MAX_SET", exerciseScope: "PUSHUPS", type: "COMPETITIVE", condition: "Réaliser la plus grande série de pompes ininterrompue." },
    { key: "king_of_set_pullups", name: "Roi des Tractions", emoji: "🧗", rarity: "COMMON", category: "PULLUPS", description: "Plus grande série de tractions", metricType: "MAX_SET", exerciseScope: "PULLUPS", type: "COMPETITIVE", condition: "Réaliser la plus grande série de tractions strictes." },
    { key: "king_of_set_squats", name: "Empereur des Squats", emoji: "🦾", rarity: "COMMON", category: "SQUATS", description: "Plus grande série de squats", metricType: "MAX_SET", exerciseScope: "SQUATS", type: "COMPETITIVE", condition: "Réaliser la plus grande série de squats ininterrompue." },
    { key: "master_thief", name: "Meilleur Voleur", emoji: "🦝", rarity: "COMMON", category: "REGULARITY", description: "Celui qui a volé le plus de badges aux autres", metricType: "STEAL_COUNT", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Dérober le plus grand nombre de badges compétitifs aux autres membres." },
    { key: "yin_yang", name: "Le Yin et le Yang", emoji: "☯️", rarity: "COMMON", category: "HOLISTIQUE", description: "Équilibre Pompes/Squats le plus proche de 100% (500 reps mini cumulées)", metricType: "BALANCE_RATIO", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Avoir le ratio le plus équilibré entre les pompes et les squats (min. 500 reps cumulées)." },
    { key: "mono_maniac", name: "Le Mono-Maniaque", emoji: "🎯", rarity: "COMMON", category: "REGULARITY", description: "Plus longue streak d'un seul exercice par jour", metricType: "MONO_EXO_STREAK", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Chaque jour, ne pratiquer qu'un seul type d'exercice pendant la plus longue période." },
    { key: "trinity", name: "La Trinité", emoji: "🔺", rarity: "COMMON", category: "HOLISTIQUE", description: "Plus longue streak avec au moins 30% Pompes, 30% Tractions, 30% Squats par jour", metricType: "TRI_EXO_STREAK", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Répartir ses efforts : au moins 30% de chaque exercice chaque jour." },
    { key: "trinity_gold", name: "Trinité d'Or", emoji: "🔱", rarity: "EPIC", category: "HOLISTIQUE", description: "Fait 3x le nombre de reps du jour (min 1 rep de chaque exo)", metricType: "TRINITY_GOLD", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Sur une journée, valider 3 fois l'objectif cumulé avec au moins 1 répétition de chaque type d'exercice." },
    { key: "trinity_ultimate", name: "Trinité Ultime", emoji: "🔱✨", rarity: "LEGENDARY", category: "HOLISTIQUE", description: "Fait l'objectif total sur CHAQUE exercice le même jour", metricType: "TRINITY_ULTIMATE", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Sur une journée, valider l'intégralité de l'objectif quotidien séparément sur les pompes, les tractions ET les squats." },
    
    // Balance Trinity (Progressive Milestones)
    { key: "trinity_balance_bronze", name: "Trinité de Bronze (Équilibre)", emoji: "🥉", rarity: "COMMON", category: "HOLISTIQUE", description: "Équilibre P/T/S (min. 15% chaque) - Vol. 60+", threshold: 60, metricType: "BALANCE_TRINITY", exerciseScope: "ALL", type: "MILESTONE", condition: "Sur une journée (min. 60 reps totales), répartir au moins 15% de l'effort sur chaque exercice (Pompes, Tractions, Squats) avec un minimum de 10 reps par exo." },
    { key: "trinity_balance_silver", name: "Trinité d'Argent (Équilibre)", emoji: "🥈", rarity: "RARE", category: "HOLISTIQUE", description: "Équilibre P/T/S (min. 22% chaque) - Vol. 90+", threshold: 90, metricType: "BALANCE_TRINITY", exerciseScope: "ALL", type: "MILESTONE", condition: "Sur une journée (min. 90 reps totales), répartir au moins 22% de l'effort sur chaque exercice avec un minimum de 10 reps par exo." },
    { key: "trinity_balance_gold", name: "Trinité d'Or (Équilibre)", emoji: "🥇", rarity: "EPIC", category: "HOLISTIQUE", description: "Équilibre P/T/S (min. 28% chaque) - Vol. 120+", threshold: 120, metricType: "BALANCE_TRINITY", exerciseScope: "ALL", type: "MILESTONE", condition: "Sur une journée (min. 120 reps totales), répartir au moins 28% de l'effort sur chaque exercice avec un minimum de 10 reps par exo." },

    { key: "quatuor_streak", name: "Le Quatuor", emoji: "💠", rarity: "COMMON", category: "HOLISTIQUE", description: "Plus longue streak avec au moins 25% P, 25% T, 25% S, 25% G par jour", metricType: "QUATUOR_STREAK", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Répartir ses efforts : au moins 25% de chaque exercice chaque jour (Gainage 🛡️ inclus)." },
    { key: "quatuor_gold", name: "Quatuor d'Or", emoji: "⚜️", rarity: "EPIC", category: "HOLISTIQUE", description: "Fait 4x le nombre de reps du jour (min 1 rep de chaque exo)", metricType: "QUATUOR_GOLD", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Sur une journée, valider 4 fois l'objectif cumulé avec une représentation des 4 disciplines." },
    { key: "quatuor_ultimate", name: "Quatuor Ultime", emoji: "⚜️✨", rarity: "LEGENDARY", category: "HOLISTIQUE", description: "Fait l'objectif total sur les 4 exercices le même jour", metricType: "QUATUOR_ULTIMATE", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Sur une journée, valider l'intégralité de l'objectif séparément sur Pompes, Tractions, Squats ET Gainage 🛡️." },

    // Balance Quatuor (Progressive Milestones)
    { key: "quatuor_balance_bronze", name: "Quatuor de Bronze (Équilibre)", emoji: "🥉", rarity: "COMMON", category: "HOLISTIQUE", description: "Équilibre P/T/S/G (min. 15% chaque) - Vol. 80+", threshold: 80, metricType: "BALANCE_QUATUOR", exerciseScope: "ALL", type: "MILESTONE", condition: "Sur une journée (min. 80 unités), répartir au moins 15% de l'effort sur chaque discipline (P, T, S, Gainage) avec un minimum de 10 unités par exo." },
    { key: "quatuor_balance_silver", name: "Quatuor d'Argent (Équilibre)", emoji: "🥈", rarity: "RARE", category: "HOLISTIQUE", description: "Équilibre P/T/S/G (min. 20% chaque) - Vol. 120+", threshold: 120, metricType: "BALANCE_QUATUOR", exerciseScope: "ALL", type: "MILESTONE", condition: "Sur une journée (min. 120 unités), répartir au moins 20% de l'effort sur chaque discipline avec un minimum de 10 unités par exo." },
    { key: "quatuor_balance_gold", name: "Quatuor d'Or (Équilibre)", emoji: "🥇", rarity: "EPIC", category: "HOLISTIQUE", description: "Équilibre P/T/S/G (min. 23% chaque) - Vol. 160+", threshold: 160, metricType: "BALANCE_QUATUOR", exerciseScope: "ALL", type: "MILESTONE", condition: "Sur une journée (min. 160 unités), répartir au moins 23% de l'effort sur chaque discipline avec un minimum de 10 unités par exo." },
    { key: "mecene_year", name: "Mécène de l'Année", emoji: "💸", rarity: "COMMON", category: "GLOBAL", description: "Plus grand donneur à la cagnotte (amendes payées)", metricType: "TOTAL_FINES_AMOUNT", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Avoir payé le plus grand montant d'amendes cumulées." },

    // B2: Series Counts (Competitive - COMMON)
    { key: "series_pushups_10", name: "Roi des Séries de 10", emoji: "🧱", rarity: "COMMON", category: "PUSHUPS", description: "Plus grand nombre de séries de 10 pompes", seriesTarget: 10, metricType: "SERIES_COUNT", exerciseScope: "PUSHUPS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 10 pompes exactement." },
    { key: "series_pushups_20", name: "Roi des Séries de 20", emoji: "🧱", rarity: "COMMON", category: "PUSHUPS", description: "Plus grand nombre de séries de 20 pompes", seriesTarget: 20, metricType: "SERIES_COUNT", exerciseScope: "PUSHUPS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 20 pompes exactement." },
    { key: "series_pushups_30", name: "Roi des Séries de 30", emoji: "🧱", rarity: "COMMON", category: "PUSHUPS", description: "Plus grand nombre de séries de 30 pompes", seriesTarget: 30, metricType: "SERIES_COUNT", exerciseScope: "PUSHUPS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 30 pompes exactement." },
    { key: "series_pullups_10", name: "Roi des Séries de 10 Tractions", emoji: "🧗", rarity: "COMMON", category: "PULLUPS", description: "Plus grand nombre de séries de 10 tractions", seriesTarget: 10, metricType: "SERIES_COUNT", exerciseScope: "PULLUPS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 10 tractions exactement." },
    { key: "series_squats_20", name: "Roi des Séries de 20 Squats", emoji: "🦵", rarity: "COMMON", category: "SQUATS", description: "Plus grand nombre de séries de 20 squats", seriesTarget: 20, metricType: "SERIES_COUNT", exerciseScope: "SQUATS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 20 squats exactement." },
    { key: "series_squats_50", name: "Roi des Séries de 50 Squats", emoji: "🦵", rarity: "COMMON", category: "SQUATS", description: "Plus grand nombre de séries de 50 squats", seriesTarget: 50, metricType: "SERIES_COUNT", exerciseScope: "SQUATS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 50 squats exactement." },
    { key: "series_squats_100", name: "Roi des Séries de 100 Squats", emoji: "🦵", rarity: "COMMON", category: "SQUATS", description: "Plus grand nombre de séries de 100 squats", seriesTarget: 100, metricType: "SERIES_COUNT", exerciseScope: "SQUATS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 100 squats exactement." },

    // B3: Unique Achievement (LEGENDARY)
    { key: "unique_pushups_50", name: "Premier 50 Pompes", emoji: "🥈", rarity: "LEGENDARY", category: "PUSHUPS", description: "Premier utilisateur à réaliser 50 pompes d'un coup", threshold: 50, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PUSHUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 50 pompes ininterrompues." },
    { key: "unique_pushups_80", name: "Premier 80 Pompes", emoji: "🥇", rarity: "LEGENDARY", category: "PUSHUPS", description: "Premier utilisateur à réaliser 80 pompes d'un coup", threshold: 80, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PUSHUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 80 pompes ininterrompues." },
    { key: "unique_pushups_100", name: "Premier 100 Pompes", emoji: "👑", rarity: "LEGENDARY", category: "PUSHUPS", description: "Premier utilisateur à réaliser 100 pompes d'un coup", threshold: 100, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PUSHUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 100 pompes ininterrompues." },
    { key: "legendary_pullups_20", name: "Premier 20 Tractions", emoji: "💎", rarity: "LEGENDARY", category: "PULLUPS", description: "Premier utilisateur à réaliser 20 tractions strictes", threshold: 20, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PULLUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 20 tractions strictes." },
    { key: "legendary_pullups_30", name: "Premier 30 Tractions", emoji: "☄️", rarity: "LEGENDARY", category: "PULLUPS", description: "Premier utilisateur à réaliser 30 tractions strictes", threshold: 30, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PULLUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 30 tractions strictes." },
    { key: "legendary_squats_150", name: "Premier 150 Squats", emoji: "🦵", rarity: "LEGENDARY", category: "SQUATS", description: "Premier utilisateur à réaliser 150 squats sans break", threshold: 150, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "SQUATS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 150 squats ininterrompus." },
    { key: "legendary_squats_300", name: "Premier 300 Squats", emoji: "🏋️", rarity: "LEGENDARY", category: "SQUATS", description: "Premier utilisateur à réaliser 300 squats sans break", threshold: 300, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "SQUATS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 300 squats ininterrompus." },
    { key: "legendary_plank_180", name: "Le Pilier", emoji: "🪵", rarity: "LEGENDARY", category: "PLANK", description: "Premier utilisateur à réaliser 3 minutes de gainage", threshold: 180, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PLANK", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 3 minutes (180s) de gainage ininterrompu." },
    { key: "legendary_plank_total_3600", name: "Le Socle", emoji: "🗽", rarity: "LEGENDARY", category: "PLANK", description: "Premier utilisateur à cumuler 1h de gainage total", threshold: 3600, isUnique: true, isTransferable: false, metricType: "FIRST_REACH_TOTAL", exerciseScope: "PLANK", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à atteindre 1 heure (3600s) de temps total sous tension." },

    // Headhunter Badges (RARE to EPIC)
    { key: "headhunter_1", name: "Chasseur Novice", emoji: "🎯", rarity: "RARE", category: "REGULARITY", description: "A décroché 1 badge à l'honneur", threshold: 1, metricType: "HEADHUNTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Décrocher son tout premier badge mis à l'honneur." },
    { key: "headhunter_3", name: "Chasseur de têtes", emoji: "🏹", rarity: "RARE", category: "REGULARITY", description: "A décroché 3 badges à l'honneur", threshold: 3, metricType: "HEADHUNTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Décrocher 3 badges mis à l'honneur." },
    { key: "headhunter_10", name: "Traqueur d'Elite", emoji: "👤", rarity: "EPIC", category: "REGULARITY", description: "A décroché 10 badges à l'honneur", threshold: 10, metricType: "HEADHUNTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Décrocher 10 badges mis à l'honneur." },
    { key: "headhunter_50", name: "Légende de la Chasse", emoji: "💀", rarity: "EPIC", category: "REGULARITY", description: "A décroché 50 badges à l'honneur", threshold: 50, metricType: "HEADHUNTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Décrocher 50 badges mis à l'honneur." },
    { key: "headhunter_100", name: "Prédateur Absolu", emoji: "👹", rarity: "LEGENDARY", category: "REGULARITY", description: "A décroché 100 badges à l'honneur", threshold: 100, metricType: "HEADHUNTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Décrocher 100 badges mis à l'honneur." },

    // New Legendary Milestones
    { key: "unique_squats_1k_day", name: "Temple du Squat", emoji: "🏛️", rarity: "LEGENDARY", category: "SQUATS", description: "Premier à faire 1000 squats in 24h", threshold: 1000, isUnique: true, isTransferable: false, metricType: "PERIOD_VOLUME", exerciseScope: "SQUATS", type: "LEGENDARY", condition: "Réaliser 1000 squats sur une seule journée.", addedAt: "2026-03-16" },
    { key: "unique_pushups_1k_week", name: "Forteresse de Fer", emoji: "🏰", rarity: "LEGENDARY", category: "PUSHUPS", description: "Premier à faire 1000 pompes en 7 jours", threshold: 1000, isUnique: true, isTransferable: false, metricType: "PERIOD_VOLUME", exerciseScope: "PUSHUPS", type: "LEGENDARY", condition: "Réaliser 1000 pompes sur une période de 7 jours glissants.", addedAt: "2026-03-16" },
    { key: "unique_pushups_1k_day", name: "Galaxie de l'Exploit", emoji: "🌌", rarity: "LEGENDARY", category: "PUSHUPS", description: "Premier à faire 1000 pompes en 1 jour", threshold: 1000, isUnique: true, isTransferable: false, metricType: "PERIOD_VOLUME", exerciseScope: "PUSHUPS", type: "LEGENDARY", condition: "Réaliser 1000 pompes en moins de 24h.", addedAt: "2026-03-16" },

    // B4: Milestones (RARE)
    { key: "centurion", name: "Le Centurion", emoji: "💯", rarity: "RARE", category: "GLOBAL", description: "Avoir fait 100 reps d'un coup", threshold: 100, isUnique: false, isTransferable: false, metricType: "MILESTONE_SET", exerciseScope: "ALL", type: "MILESTONE", condition: "Réaliser une série de 100 répétitions ou plus (tous exercices)." },
    { key: "general_1k", name: "Le Soldat", emoji: "🔫", rarity: "RARE", category: "GLOBAL", description: "1 000 reps cumulées", threshold: 1000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 1 000 répétitions cumulées au total." },
    { key: "general_5k", name: "Le Sergent", emoji: "🛡️", rarity: "RARE", category: "GLOBAL", description: "5 000 reps cumulées", threshold: 5000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 5 000 répétitions cumulées au total." },
    { key: "general_10k", name: "Le Général", emoji: "🏰", rarity: "RARE", category: "GLOBAL", description: "10 000 reps cumulées", threshold: 10000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 10 000 répétitions cumulées au total." },
    { key: "general_20k", name: "Le Warlord", emoji: "⚔️", rarity: "EPIC", category: "GLOBAL", description: "20 000 reps cumulées", threshold: 20000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 20 000 répétitions cumulées au total." },
    { key: "general_40k", name: "Le Conquérant", emoji: "🌍", rarity: "EPIC", category: "GLOBAL", description: "40 000 reps cumulées", threshold: 40000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 40 000 répétitions cumulées au total." },
    { key: "general_60k", name: "Le Demi-Dieu", emoji: "⚡", rarity: "LEGENDARY", category: "GLOBAL", description: "60 000 reps cumulées", threshold: 60000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 60 000 répétitions cumulées au total." },
    { key: "general_100k", name: "L'Immortel", emoji: "🌌", rarity: "LEGENDARY", category: "GLOBAL", description: "100 000 reps cumulées", threshold: 100000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 100 000 répétitions cumulées au total." },

    // Exercise Specific Milestones (RARE)
    { key: "pushups_1k", name: "Pousseur Novice", emoji: "🥉", rarity: "RARE", category: "PUSHUPS", threshold: 1000, metricType: "MILESTONE_TOTAL", exerciseScope: "PUSHUPS", type: "MILESTONE", description: "1 000 Pompes cumulées", condition: "Atteindre 1 000 pompes cumulées." },
    { key: "pushups_10k", name: "Pousseur Expert", emoji: "🥈", rarity: "RARE", category: "PUSHUPS", threshold: 10000, metricType: "MILESTONE_TOTAL", exerciseScope: "PUSHUPS", type: "MILESTONE", description: "10 000 Pompes cumulées", condition: "Atteindre 10 000 pompes cumulées." },
    { key: "pushups_50k", name: "Dieu des Pompes", emoji: "🥇", rarity: "EPIC", category: "PUSHUPS", threshold: 50000, metricType: "MILESTONE_TOTAL", exerciseScope: "PUSHUPS", type: "MILESTONE", description: "50 000 Pompes cumulées", condition: "Atteindre 50 000 pompes cumulées." },
    { key: "squats_1k", name: "Cuisses de Poulet", emoji: "🍗", rarity: "RARE", category: "SQUATS", threshold: 1000, metricType: "MILESTONE_TOTAL", exerciseScope: "SQUATS", type: "MILESTONE", description: "1 000 Squats cumulés", condition: "Atteindre 1 000 squats cumulés." },
    { key: "squats_10k", name: "Cuisses d'Acier", emoji: "🦾", rarity: "RARE", category: "SQUATS", threshold: 10000, metricType: "MILESTONE_TOTAL", exerciseScope: "SQUATS", type: "MILESTONE", description: "10 000 Squats cumulés", condition: "Atteindre 10 000 squats cumulés." },
    { key: "squats_50k", name: "Pilier de la Terre", emoji: "🏛️", rarity: "EPIC", category: "SQUATS", threshold: 50000, metricType: "MILESTONE_TOTAL", exerciseScope: "SQUATS", type: "MILESTONE", description: "50 000 Squats cumulés", condition: "Atteindre 50 000 squats cumulés." },
    { key: "squats_100k", name: "Atlas", emoji: "🌍", rarity: "LEGENDARY", category: "SQUATS", threshold: 100000, metricType: "MILESTONE_TOTAL", exerciseScope: "SQUATS", type: "MILESTONE", description: "100 000 Squats cumulés", condition: "Atteindre 100 000 squats cumulés." },
    { key: "pullups_1k", name: "Grimpette", emoji: "🧗", rarity: "RARE", category: "PULLUPS", threshold: 1000, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", description: "1 000 Tractions cumulées", condition: "Atteindre 1 000 tractions cumulées." },
    { key: "pullups_5k", name: "Tarzan", emoji: "🌴", rarity: "RARE", category: "PULLUPS", threshold: 5000, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", description: "5 000 Tractions cumulées", condition: "Atteindre 5 000 tractions cumulées." },
    { key: "pullups_10k", name: "Spiderman", emoji: "🕷️", rarity: "EPIC", category: "PULLUPS", threshold: 10000, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", description: "10 000 Tractions cumulées", condition: "Atteindre 10 000 tractions cumulées." },
    { key: "pullups_50k", name: "Lévitation", emoji: "🧞", rarity: "LEGENDARY", category: "PULLUPS", threshold: 50000, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", description: "50 000 Tractions cumulées", condition: "Atteindre 50 000 tractions cumulées." },

    // Time Awards & Streaks (RARE)
    { key: "survivor_30d", name: "Le Survivant", emoji: "🛡️", rarity: "RARE", category: "REGULARITY", threshold: 30, metricType: "STREAK_NO_FINES", type: "MILESTONE", exerciseScope: "ALL", description: "30 jours sans amende", condition: "Enchaîner 30 jours consécutifs sans recevoir d'amende." },
    { key: "survivor_90d", name: "Le Fantôme", emoji: "🥷", rarity: "EPIC", category: "REGULARITY", threshold: 90, metricType: "STREAK_NO_FINES", type: "MILESTONE", exerciseScope: "ALL", description: "90 jours sans amende", condition: "Enchaîner 90 jours consécutifs sans recevoir d'amende." },
    { key: "early_bird_7", name: "Lève-tôt (7j)", emoji: "☀️", rarity: "RARE", category: "REGULARITY", threshold: 7, metricType: "TIME_AWARD", type: "MILESTONE", exerciseScope: "ALL", description: "7 j. consécutifs avant 6h", condition: "Réaliser une série avant 6h00 pendant 7 jours consécutifs." },
    { key: "night_owl_7", name: "Oiseau de Nuit (7j)", emoji: "🌙", rarity: "RARE", category: "REGULARITY", threshold: 7, metricType: "TIME_AWARD_LATE", type: "MILESTONE", exerciseScope: "ALL", description: "7 j. consécutifs après 22h", condition: "Réaliser une série après 22h00 pendant 7 jours consécutifs." },
    { key: "sprinter_10", name: "Éclair", emoji: "⚡", rarity: "RARE", category: "REGULARITY", threshold: 10, metricType: "SPRINTER_COUNT", type: "MILESTONE", exerciseScope: "ALL", description: "10 fois premier à valider", condition: "Être le premier à valider son objectif quotidien 10 jours différents." },

    // V9: Progressive Early Bird & Night Owl (2026-05-01 onwards)
    { key: "early_bird_p1", name: "Lève-tôt (Niv. 1)", emoji: "🌅", rarity: "COMMON", category: "REGULARITY", threshold: 7, metricType: "EARLY_COUNT", type: "MILESTONE", exerciseScope: "ALL", description: "7 réveils matinaux au total (avant 6h)", condition: "Réaliser une série avant 6h00 lors de 7 journées différentes (cumulatif après le 1er mai 2026).", addedAt: "2026-05-01" },
    { key: "early_bird_p2", name: "Lève-tôt (Niv. 2)", emoji: "🌄", rarity: "RARE", category: "REGULARITY", threshold: 3, metricType: "EARLY_STREAK", type: "MILESTONE", exerciseScope: "ALL", description: "3 jours consécutifs avant 6h", condition: "Réaliser une série avant 6h00 pendant 3 jours consécutifs (après le 1er mai 2026).", addedAt: "2026-05-01" },
    { key: "early_bird_p3", name: "Lève-tôt (Niv. 3)", emoji: "☀️", rarity: "EPIC", category: "REGULARITY", threshold: 7, metricType: "EARLY_STREAK", type: "MILESTONE", exerciseScope: "ALL", description: "7 jours consécutifs avant 6h", condition: "Réaliser une série avant 6h00 pendant 7 jours consécutifs (après le 1er mai 2026).", addedAt: "2026-05-01" },
    { key: "night_owl_p1", name: "Oiseau de Nuit (Niv. 1)", emoji: "🌌", rarity: "COMMON", category: "REGULARITY", threshold: 7, metricType: "LATE_COUNT", type: "MILESTONE", exerciseScope: "ALL", description: "7 sessions tardives au total (après 22h)", condition: "Réaliser une série après 22h00 lors de 7 journées différentes (cumulatif après le 1er mai 2026).", addedAt: "2026-05-01" },
    { key: "night_owl_p2", name: "Oiseau de Nuit (Niv. 2)", emoji: "🌃", rarity: "RARE", category: "REGULARITY", threshold: 3, metricType: "LATE_STREAK", type: "MILESTONE", exerciseScope: "ALL", description: "3 jours consécutifs après 22h", condition: "Réaliser une série après 22h00 pendant 3 jours consécutifs (après le 1er mai 2026).", addedAt: "2026-05-01" },
    { key: "night_owl_p3", name: "Oiseau de Nuit (Niv. 3)", emoji: "🌙", rarity: "EPIC", category: "REGULARITY", threshold: 7, metricType: "LATE_STREAK", type: "MILESTONE", exerciseScope: "ALL", description: "7 jours consécutifs après 22h", condition: "Réaliser une série après 22h00 pendant 7 jours consécutifs (après le 1er mai 2026).", addedAt: "2026-05-01" },

    // V8: New Chronological Events & Specials
    { key: "st_patrick", name: "Trèfle de Chance", emoji: "🍀", rarity: "EPIC", category: "GLOBAL", metricType: "DATE_AWARD_HARD", type: "EVENT", exerciseScope: "ALL", description: "S'être entraîné le 17 mars", condition: "Réaliser au moins une série le jour de la Saint-Patrick (17 mars)." },
    { key: "st_patrick_gold", name: "Trèfle d'Or", emoji: "☘️", rarity: "LEGENDARY", category: "GLOBAL", metricType: "DATE_AWARD_HARD_GOLD", type: "EVENT", exerciseScope: "ALL", description: "Quota total validé le 17 mars", condition: "Atteindre le quota total du jour le jour de la Saint-Patrick." },
    { key: "st_marvin", name: "Saint Marvin", emoji: "🔥", rarity: "EPIC", category: "GLOBAL", metricType: "MARVIN_AWARD", type: "EVENT", exerciseScope: "ALL", description: "Avoir égalé ou battu EMBI le 08 Mars", condition: "Le 8 mars, égaler ou dépasser le volume de répétitions d'EMBI." },
    { key: "april_fools_1", name: "Le Gran Blanc", emoji: "🦈", rarity: "EPIC", category: "GLOBAL", metricType: "APRIL_FOOLS_TIER", type: "EVENT", exerciseScope: "ALL", description: "Top 1 volume du 1er avril", condition: "Terminer à la 1ère place du classement de volume le 1er avril." },
    { key: "april_fools_2", name: "Gros Brochet", emoji: "🐊", rarity: "EPIC", category: "GLOBAL", metricType: "APRIL_FOOLS_TIER", type: "EVENT", exerciseScope: "ALL", description: "Top 2 volume du 1er avril", condition: "Terminer à la 2ème place du classement de volume le 1er avril." },
    { key: "april_fools_3", name: "Saumon Agile", emoji: "🎏", rarity: "EPIC", category: "GLOBAL", metricType: "APRIL_FOOLS_TIER", type: "EVENT", exerciseScope: "ALL", description: "Top 3 volume du 1er avril", condition: "Terminer à la 3ème place du classement de volume le 1er avril." },
    { key: "april_fools_4", name: "Truite Commune", emoji: "🐟", rarity: "EPIC", category: "GLOBAL", metricType: "APRIL_FOOLS_TIER", type: "EVENT", exerciseScope: "ALL", description: "Top 4 volume du 1er avril", condition: "Terminer à la 4ème place du classement de volume le 1er avril." },
    { key: "april_fools_5", name: "Petit Gardon", emoji: "🐡", rarity: "EPIC", category: "GLOBAL", metricType: "APRIL_FOOLS_TIER", type: "EVENT", exerciseScope: "ALL", description: "Top 5 volume du 1er avril", condition: "Terminer à la 5ème place du classement de volume le 1er avril." },
    { key: "april_fools_6", name: "Minuscule Sardine", emoji: "🐠", rarity: "RARE", category: "GLOBAL", metricType: "APRIL_FOOLS_TIER", type: "EVENT", exerciseScope: "ALL", description: "S'être entraîné le 1er avril (hors top 5)", condition: "S'être entraîné le 1er avril (hors top 5)." },
    { key: "st_patrick_diamond", name: "Trèfle de Diamant", emoji: "💎", rarity: "LEGENDARY", category: "GLOBAL", metricType: "DATE_COMPETITIVE_REPS", type: "COMPETITIVE", exerciseScope: "ALL", description: "Le plus gros volume du 17 mars", condition: "Terminer à la 1ère place du classement de volume le jour de la Saint-Patrick.", addedAt: "2026-03-14" },
    { key: "st_patrick_pushups", name: "Trèfle d'Émeraude", emoji: "💚", rarity: "EPIC", category: "PUSHUPS", metricType: "DATE_COMPETITIVE_SET_PUSHUPS", type: "COMPETITIVE", exerciseScope: "PUSHUPS", description: "Plus grosse série de pompes le 17 mars", condition: "Réaliser la plus grosse série de pompes le jour de la Saint-Patrick.", addedAt: "2026-03-14" },
    { key: "st_patrick_pullups", name: "Trèfle de Saphir", emoji: "💙", rarity: "EPIC", category: "PULLUPS", metricType: "DATE_COMPETITIVE_SET_PULLUPS", type: "COMPETITIVE", exerciseScope: "PULLUPS", description: "Plus grosse série de tractions le 17 mars", condition: "Réaliser la plus grosse série de tractions le jour de la Saint-Patrick.", addedAt: "2026-03-14" },
    { key: "st_patrick_squats", name: "Trèfle de Rubis", emoji: "❤️", rarity: "EPIC", category: "SQUATS", metricType: "DATE_COMPETITIVE_SET_SQUATS", type: "COMPETITIVE", exerciseScope: "SQUATS", description: "Plus grosse série de squats le 17 mars", condition: "Réaliser la plus grosse série de squats le jour de la Saint-Patrick.", addedAt: "2026-03-14" },

    // Monthly Competitive (EPIC)
    { key: "month_top_volume", name: "Souverain du Mois", emoji: "🏛️", rarity: "EPIC", category: "GLOBAL", metricType: "MONTH_TOP_VOLUME", type: "COMPETITIVE", exerciseScope: "ALL", description: "Record de volume mensuel. Depuis mai 2026 : 500 XP volatiles + Capture de Gloire en fin de mois.", condition: "Terminer le mois avec le volume total le plus élevé. Le titre est remis en jeu chaque mois.", addedAt: "2026-03-14" },
    { key: "month_top_pushups_set", name: "Piston du Mois", emoji: "🦾", rarity: "EPIC", category: "PUSHUPS", metricType: "MONTH_TOP_SET", type: "COMPETITIVE", exerciseScope: "PUSHUPS", description: "Plus grosse série de pompes du mois. Depuis mai 2026 : 500 XP volatiles + Capture de Gloire.", condition: "Détenir la plus grosse série de pompes validée du mois.", addedAt: "2026-03-14" },
    { key: "month_top_pullups_set", name: "Yamakasi du Mois", emoji: "🧗", rarity: "EPIC", category: "PULLUPS", metricType: "MONTH_TOP_SET", type: "COMPETITIVE", exerciseScope: "PULLUPS", description: "Plus grosse série de tractions du mois. Depuis mai 2026 : 500 XP volatiles + Capture de Gloire.", condition: "Détenir la plus grosse série de tractions validée du mois.", addedAt: "2026-03-14" },
    { key: "month_top_squats_set", name: "Colosse du Mois", emoji: "🗿", rarity: "EPIC", category: "SQUATS", metricType: "MONTH_TOP_SET", type: "COMPETITIVE", exerciseScope: "SQUATS", description: "Plus grosse série de squats du mois. Depuis mai 2026 : 500 XP volatiles + Capture de Gloire.", condition: "Détenir la plus grosse série de squats validée du mois.", addedAt: "2026-03-14" },
    { key: "month_top_plank_set", name: "La Stèle du Mois", emoji: "🪦", rarity: "EPIC", category: "PLANK", metricType: "MONTH_TOP_SET", type: "COMPETITIVE", exerciseScope: "PLANK", description: "Plus grosse série de gainage du mois. Depuis mai 2026 : 500 XP volatiles + Capture de Gloire.", condition: "Détenir la plus grosse série de gainage 🛡️ du mois.", addedAt: "2026-05-01" },
    { key: "month_total_pushups", name: "Usine à Pompes", emoji: "🛠️", rarity: "RARE", category: "PUSHUPS", metricType: "MONTH_TOTAL_EXO", type: "COMPETITIVE", exerciseScope: "PUSHUPS", description: "Record de volume pompes. Depuis mai 2026 : 500 XP volatiles + Capture de Gloire.", condition: "Terminer le mois avec le plus gros volume de pompes.", addedAt: "2026-03-14" },
    { key: "month_total_pullups", name: "Acrobate du Mois", emoji: "🎪", rarity: "RARE", category: "PULLUPS", metricType: "MONTH_TOTAL_EXO", type: "COMPETITIVE", exerciseScope: "PULLUPS", description: "Record de volume tractions. Depuis mai 2026 : 500 XP volatiles + Capture de Gloire.", condition: "Terminer le mois avec le plus gros volume de tractions.", addedAt: "2026-03-14" },
    { key: "month_total_squats", name: "Atlas du Mois", emoji: "🌍", rarity: "RARE", category: "SQUATS", metricType: "MONTH_TOTAL_EXO", type: "COMPETITIVE", exerciseScope: "SQUATS", description: "Record de volume squats. Depuis mai 2026 : 500 XP volatiles + Capture de Gloire.", condition: "Terminer le mois avec le plus gros volume de squats.", addedAt: "2026-03-14" },
    { key: "month_total_plank", name: "Le Ciment du Mois", emoji: "🫗", rarity: "RARE", category: "PLANK", metricType: "MONTH_TOTAL_EXO", type: "COMPETITIVE", exerciseScope: "PLANK", description: "Record de volume gainage. Depuis mai 2026 : 500 XP volatiles + Capture de Gloire.", condition: "Terminer le mois avec le plus gros volume de gainage.", addedAt: "2026-05-01" },

    // V8: New Chronological Events & Specials
    { key: "equinox_spring", name: "Maître de l'Équinoxe (Print.)", emoji: "🌱", rarity: "EPIC", category: "GLOBAL", metricType: "DATE_AWARD_HARD", type: "EVENT", exerciseScope: "ALL", description: "Ratio 50/50 parfait au 20 Mars", condition: "Avoir un ratio Pompes/Squats de exactement 50/50 le jour de l'équinoxe de printemps.", addedAt: "2026-03-15" },
    { key: "st_kevin", name: "Saint Kevin", emoji: "🥛", rarity: "EPIC", category: "REGULARITY", metricType: "BEAT_OWNER", type: "EVENT", exerciseScope: "ALL", description: "Avoir battu Milkardashian le 3 Juin", condition: "Le 3 juin, dépasser le volume de répétitions de Milkardashian.", addedAt: "2026-03-15" },
    { key: "st_thomas", name: "Saint Thomas", emoji: "🍺", rarity: "EPIC", category: "REGULARITY", metricType: "BEAT_OWNER", type: "EVENT", exerciseScope: "ALL", description: "Avoir battu Neuneu le 3 Juillet", condition: "Le 3 juillet, dépasser le volume de répétitions de Neuneu.", addedAt: "2026-03-15" },
    { key: "st_damien_sept", name: "Saint Damien", emoji: "⚔️", rarity: "EPIC", category: "REGULARITY", metricType: "BEAT_OWNER", type: "EVENT", exerciseScope: "ALL", description: "Avoir battu Mools le 26 Septembre", condition: "Le 26 septembre, dépasser le volume de répétitions de Mools.", addedAt: "2026-03-15" },
    { key: "equinox_autumn", name: "Maître de l'Équinoxe (Aut.)", emoji: "🍂", rarity: "EPIC", category: "GLOBAL", metricType: "DATE_AWARD_HARD", type: "EVENT", exerciseScope: "ALL", description: "Ratio 50/50 parfait au 22 Septembre", condition: "Avoir un ratio Pompes/Squats de exactement 50/50 le jour de l'équinoxe d'automne.", addedAt: "2026-03-15" },
    { key: "st_xavier", name: "Saint Xavier", emoji: "❌", rarity: "EPIC", category: "REGULARITY", metricType: "BEAT_OWNER", type: "EVENT", exerciseScope: "ALL", description: "Avoir battu Xa le 3 Décembre", condition: "Le 3 décembre, dépasser le volume de répétitions de Xa.", addedAt: "2026-03-15" },
    { key: "solstice_summer", name: "Roi du Soleil", emoji: "☀️", rarity: "EPIC", category: "GLOBAL", metricType: "DATE_AWARD_HARD", type: "EVENT", exerciseScope: "ALL", description: "900 reps le 21 Juin", condition: "Réaliser au moins 900 répétitions le jour du solstice d'été (15h de jour).", addedAt: "2026-03-15" },
    { key: "solstice_winter", name: "Guerrier du Froid", emoji: "❄️", rarity: "EPIC", category: "GLOBAL", metricType: "DATE_AWARD_HARD", type: "EVENT", exerciseScope: "ALL", description: "1 rep/h pendant 12h le 21 Décembre", condition: "Réaliser au moins une répétition par heure pendant 12 heures consécutives le jour du solstice d'hiver.", addedAt: "2026-03-15" },
    { key: "noel_sapin", name: "Cadeau Suprême", emoji: "🎄", rarity: "LEGENDARY", category: "GLOBAL", metricType: "DATE_AWARD_HARD", type: "EVENT", exerciseScope: "ALL", description: "Série Sapin (1 à 15 sur CHAQUE exo) le 25 Décembre", condition: "Le jour de Noël, réaliser une série de 1 à 15 répétitions sur les pompes, les tractions ET les squats.", addedAt: "2026-03-15" },
    { key: "st_nicolas_6", name: "Petit Saint", emoji: "🍊", rarity: "EPIC", category: "GLOBAL", metricType: "DATE_AWARD_HARD", type: "EVENT", exerciseScope: "ALL", description: "Total fini par 6 le 6 Décembre", condition: "Le jour de la Saint-Nicolas, avoir un total quotidien finissant par le chiffre 6.", addedAt: "2026-03-15" },

    // Sally Up & Flambeau
    { key: "sally_participation", name: "Soldat de Sally", emoji: "🎶", rarity: "RARE", category: "GLOBAL", metricType: "SALLY_PART", type: "EVENT", exerciseScope: "ALL", description: "A participé au challenge Bring Sally Up", condition: "Participer au défi mensuel 'Bring Sally Up' le dernier jour du mois.", addedAt: "2026-03-15" },
    { key: "sally_podium_1", name: "Légende de Sally", emoji: "🏆", rarity: "LEGENDARY", category: "GLOBAL", metricType: "SALLY_PODIUM", type: "EVENT", exerciseScope: "ALL", description: "Top 1 Bring Sally Up du mois", condition: "Terminer à la 1ère place du classement 'Bring Sally Up' du mois.", addedAt: "2026-03-15" },
    { key: "torch_legacy", name: "Gardien du Flambeau", emoji: "🚩", rarity: "EPIC", category: "REGULARITY", metricType: "TORCH_STREAK", type: "MILESTONE", exerciseScope: "ALL", description: "Badge évolutif (300-3000 XP) selon votre record de jours consécutifs avec le Flambeau.", condition: "Obtenu après avoir perdu le Flambeau. Évolue selon le record de jours : Éclaireur (300), Gardien (500), Sentinelle (1k), Seigneur (1.8k), Feu Sacré (3k).", addedAt: "2026-03-15" },
    { key: "murph_hero", name: "Héros du D-Day", emoji: "🎖️", rarity: "LEGENDARY", category: "GLOBAL", metricType: "SPECIAL_WORKOUT", type: "EVENT", exerciseScope: "ALL", description: "A réalisé le MURPH lors de la semaine du 6 Juin", condition: "Valider l'entraînement spécial MURPH pendant la semaine commémorative du D-Day.", addedAt: "2026-03-15" },
    { key: "torch_daily", name: "Flambeau Quotidien", emoji: "🔥", rarity: "COMMON", category: "REGULARITY", metricType: "TECHNICAL", type: "TECHNICAL", exerciseScope: "ALL", description: "Badge technique pour le premier validateur du jour", condition: "Être le premier à valider son quota.", addedAt: "2026-04-29" },

    // Special Workouts - Premier Exploit
    { key: "workout_workout-01-the-first_std", name: "Explorateur de l'Exploit", emoji: "🧭", rarity: "RARE", category: "GLOBAL", metricType: "SPECIAL_WORKOUT", type: "EVENT", exerciseScope: "ALL", description: "Badge de participation (0 XP). A complété l'entraînement 'Premier Exploit'.", condition: "Réaliser l'intégralité des exercices de l'entraînement spécial inaugural.", addedAt: "2026-03-17" },
    { key: "workout_workout-01-the-first_plat", name: "Platine : Premier Exploit", emoji: "💎", rarity: "LEGENDARY", category: "GLOBAL", metricType: "SPECIAL_WORKOUT", type: "COMPETITIVE", exerciseScope: "ALL", description: "Détenteur du record sur l'entraînement 'Premier Exploit'", condition: "Détenir le meilleur temps sur l'entraînement 'Premier Exploit'. Le titre est transférable si le record est battu.", addedAt: "2026-03-17" },

    // Special Workouts - Le Souffle du Printemps
    { key: "workout_workout-02-spring_std", name: "Explorateur du Printemps", emoji: "🍃", rarity: "RARE", category: "GLOBAL", metricType: "SPECIAL_WORKOUT", type: "EVENT", exerciseScope: "ALL", description: "Badge de participation (0 XP). A complété l'entraînement 'Le Souffle du Printemps'.", condition: "Réaliser l'intégralité des exercices de l'entraînement spécial du printemps.", addedAt: "2026-03-21" },
    { key: "workout_workout-02-spring_plat", name: "Zéphir d'Or", emoji: "🌬️", rarity: "LEGENDARY", category: "GLOBAL", metricType: "SPECIAL_WORKOUT", type: "COMPETITIVE", exerciseScope: "ALL", description: "Détenteur du record sur l'entraînement 'Le Souffle du Printemps'", condition: "Détenir le meilleur temps sur l'entraînement 'Le Souffle du Printemps'. Le titre est transférable si le record est battu.", addedAt: "2026-03-21" },

    // Special Workouts - La Grande Pyramide
    { key: "workout_workout-03-pyramid_std", name: "Explorateur de la Pyramide", emoji: "🏜️", rarity: "RARE", category: "GLOBAL", metricType: "SPECIAL_WORKOUT", type: "EVENT", exerciseScope: "ALL", description: "Badge de participation (0 XP). A complété l'entraînement 'La Grande Pyramide'.", condition: "Réaliser l'intégralité des exercices de l'entraînement spécial pyramidal.", addedAt: "2026-04-27" },
    { key: "workout_workout-03-pyramid_plat", name: "Le Pharaon", emoji: "👑", rarity: "LEGENDARY", category: "GLOBAL", metricType: "SPECIAL_WORKOUT", type: "COMPETITIVE", exerciseScope: "ALL", description: "Détenteur du record sur l'entraînement 'La Grande Pyramide'", condition: "Détenir le meilleur temps sur l'entraînement 'La Grande Pyramide'. Le titre est transférable si le record est battu.", addedAt: "2026-04-27" }
];
