export const BADGE_DEFINITIONS = [
    // B1: Competitive Transferable
    { key: "big_flexer", name: "Gros Flexeur", emoji: "🚀", description: "Meilleur bonus reps (Total - Cible) sur une journée", metricType: "MAX_BONUS", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Obtenir le plus gros surplus de répétitions par rapport à l'objectif sur une journée." },
    { key: "regular_flexer", name: "Flexeur Régulier", emoji: "🔥", description: "Plus longue streak de jours avec bonus > 0", metricType: "BONUS_STREAK", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Maintenir la plus longue série de jours consécutifs avec un surplus de répétitions." },
    { key: "perfect_soldier", name: "Le bon petit nazi", emoji: "👨🏻", description: "Celui qui fait exactement le bon nombre de reps chaque jour. Tie-break: plus longue streak.", metricType: "PERFECT_TARGET_STREAK", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Atteindre exactement l'objectif quotidien, sans une répétition de plus ni de moins." },
    { key: "king_of_set_all", name: "Roi de la Plus Longue Série", emoji: "👑", description: "Plus grande série réalisée (tous exos)", metricType: "MAX_SET", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Réaliser la plus grande série de répétitions ininterrompue, tous exercices confondus." },
    { key: "king_of_set_pushups", name: "Furie des Pompes", emoji: "💪", description: "Plus grande série de pompes", metricType: "MAX_SET", exerciseScope: "PUSHUPS", type: "COMPETITIVE", condition: "Réaliser la plus grande série de pompes ininterrompue." },
    { key: "king_of_set_pullups", name: "Roi des Tractions", emoji: "🧗", description: "Plus grande série de tractions", metricType: "MAX_SET", exerciseScope: "PULLUPS", type: "COMPETITIVE", condition: "Réaliser la plus grande série de tractions strictes." },
    { key: "king_of_set_squats", name: "Empereur des Squats", emoji: "🦾", description: "Plus grande série de squats", metricType: "MAX_SET", exerciseScope: "SQUATS", type: "COMPETITIVE", condition: "Réaliser la plus grande série de squats ininterrompue." },
    { key: "master_thief", name: "Meilleur Voleur", emoji: "🦝", description: "Celui qui a volé le plus de badges aux autres", metricType: "STEAL_COUNT", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Dérober le plus grand nombre de badges compétitifs aux autres membres." },
    { key: "yin_yang", name: "Le Yin et le Yang", emoji: "☯️", description: "Équilibre Pompes/Squats le plus proche de 100% (500 reps mini cumulées)", metricType: "BALANCE_RATIO", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Avoir le ratio le plus équilibré entre les pompes et les squats (min. 500 reps cumulées)." },
    { key: "mono_maniac", name: "Le Mono-Maniaque", emoji: "🎯", description: "Plus longue streak d'un seul exercice par jour", metricType: "MONO_EXO_STREAK", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Chaque jour, ne pratiquer qu'un seul type d'exercice pendant la plus longue période." },
    { key: "trinity", name: "La Trinité", emoji: "🔺", description: "Plus longue streak avec au moins 30% Pompes, 30% Tractions, 30% Squats par jour", metricType: "TRI_EXO_STREAK", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Répartir ses efforts : au moins 30% de chaque exercice chaque jour." },
    { key: "mecene_year", name: "Mécène de l'Année", emoji: "💸", description: "Plus grand donneur à la cagnotte (amendes payées)", metricType: "TOTAL_FINES_AMOUNT", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Avoir payé le plus grand montant d'amendes cumulées." },

    // B2: Series Counts (Competitive)
    { key: "series_pushups_10", name: "Roi des Séries de 10", emoji: "🧱", description: "Plus grand nombre de séries de 10 pompes", seriesTarget: 10, metricType: "SERIES_COUNT", exerciseScope: "PUSHUPS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 10 pompes exactement." },
    { key: "series_pushups_20", name: "Roi des Séries de 20", emoji: "🧱", description: "Plus grand nombre de séries de 20 pompes", seriesTarget: 20, metricType: "SERIES_COUNT", exerciseScope: "PUSHUPS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 20 pompes exactement." },
    { key: "series_pushups_30", name: "Roi des Séries de 30", emoji: "🧱", description: "Plus grand nombre de séries de 30 pompes", seriesTarget: 30, metricType: "SERIES_COUNT", exerciseScope: "PUSHUPS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 30 pompes exactement." },
    { key: "series_pullups_10", name: "Roi des Séries de 10 Tractions", emoji: "🧗", description: "Plus grand nombre de séries de 10 tractions", seriesTarget: 10, metricType: "SERIES_COUNT", exerciseScope: "PULLUPS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 10 tractions exactement." },
    { key: "series_squats_20", name: "Roi des Séries de 20 Squats", emoji: "🦵", description: "Plus grand nombre de séries de 20 squats", seriesTarget: 20, metricType: "SERIES_COUNT", exerciseScope: "SQUATS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 20 squats exactement." },
    { key: "series_squats_50", name: "Roi des Séries de 50 Squats", emoji: "🦵", description: "Plus grand nombre de séries de 50 squats", seriesTarget: 50, metricType: "SERIES_COUNT", exerciseScope: "SQUATS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 50 squats exactement." },
    { key: "series_squats_100", name: "Roi des Séries de 100 Squats", emoji: "🦵", description: "Plus grand nombre de séries de 100 squats", seriesTarget: 100, metricType: "SERIES_COUNT", exerciseScope: "SQUATS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 100 squats exactement." },

    // B3: Unique Achievement (Non-transferable Legendary)
    { key: "unique_pushups_50", name: "Premier 50 Pompes", emoji: "🥈", description: "Premier utilisateur à réaliser 50 pompes d'un coup", threshold: 50, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PUSHUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 50 pompes ininterrompues." },
    { key: "unique_pushups_80", name: "Premier 80 Pompes", emoji: "🥇", description: "Premier utilisateur à réaliser 80 pompes d'un coup", threshold: 80, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PUSHUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 80 pompes ininterrompues." },
    { key: "unique_pushups_100", name: "Premier 100 Pompes", emoji: "👑", description: "Premier utilisateur à réaliser 100 pompes d'un coup", threshold: 100, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PUSHUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 100 pompes ininterrompues." },
    { key: "legendary_pullups_20", name: "Premier 20 Tractions", emoji: "💎", description: "Premier utilisateur à réaliser 20 tractions strictes", threshold: 20, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PULLUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 20 tractions strictes." },
    { key: "legendary_pullups_30", name: "Premier 30 Tractions", emoji: "☄️", description: "Premier utilisateur à réaliser 30 tractions strictes", threshold: 30, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PULLUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 30 tractions strictes." },
    { key: "legendary_squats_150", name: "Premier 150 Squats", emoji: "🦵", description: "Premier utilisateur à réaliser 150 squats sans break", threshold: 150, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "SQUATS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 150 squats ininterrompus." },
    { key: "legendary_squats_300", name: "Premier 300 Squats", emoji: "🏋️", description: "Premier utilisateur à réaliser 300 squats sans break", threshold: 300, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "SQUATS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 300 squats ininterrompus." },

    // B4: Milestones (Individual)
    { key: "centurion", name: "Le Centurion", emoji: "💯", description: "Avoir fait 100 reps d'un coup", threshold: 100, isUnique: false, isTransferable: false, metricType: "MILESTONE_SET", exerciseScope: "ALL", type: "MILESTONE", condition: "Réaliser une série de 100 répétitions ou plus (tous exercices)." },

    // Milestones (Totals Globaux)
    { key: "general_1k", name: "Le Soldat", emoji: "🔫", description: "1 000 reps cumulées", threshold: 1000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 1 000 répétitions cumulées au total." },
    { key: "general_5k", name: "Le Sergent", emoji: "🛡️", description: "5 000 reps cumulées", threshold: 5000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 5 000 répétitions cumulées au total." },
    { key: "general_10k", name: "Le Général", emoji: "🏰", description: "10 000 reps cumulées", threshold: 10000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 10 000 répétitions cumulées au total." },
    { key: "general_20k", name: "Le Warlord", emoji: "⚔️", description: "20 000 reps cumulées", threshold: 20000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 20 000 répétitions cumulées au total." },
    { key: "general_40k", name: "Le Conquérant", emoji: "🌍", description: "40 000 reps cumulées", threshold: 40000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 40 000 répétitions cumulées au total." },
    { key: "general_60k", name: "Le Demi-Dieu", emoji: "⚡", description: "60 000 reps cumulées", threshold: 60000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 60 000 répétitions cumulées au total." },
    { key: "general_100k", name: "L'Immortel", emoji: "🌌", description: "100 000 reps cumulées", threshold: 100000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 100 000 répétitions cumulées au total." },

    // Milestones (Pompes)
    { key: "pushups_1k", name: "Pousseur Novice", emoji: "🥉", description: "1 000 Pompes cumulées", threshold: 1000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "PUSHUPS", type: "MILESTONE", condition: "Atteindre 1 000 pompes cumulées." },
    { key: "pushups_10k", name: "Pousseur Expert", emoji: "🥈", description: "10 000 Pompes cumulées", threshold: 10000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "PUSHUPS", type: "MILESTONE", condition: "Atteindre 10 000 pompes cumulées." },
    { key: "pushups_50k", name: "Dieu des Pompes", emoji: "🥇", description: "50 000 Pompes cumulées", threshold: 50000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "PUSHUPS", type: "MILESTONE", condition: "Atteindre 50 000 pompes cumulées." },

    // Milestones (Squats)
    { key: "squats_1k", name: "Cuisses de Poulet", emoji: "🍗", description: "1 000 Squats cumulés", threshold: 1000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "SQUATS", type: "MILESTONE", condition: "Atteindre 1 000 squats cumulés." },
    { key: "squats_10k", name: "Cuisses d'Acier", emoji: "🦾", description: "10 000 Squats cumulés", threshold: 10000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "SQUATS", type: "MILESTONE", condition: "Atteindre 10 000 squats cumulés." },
    { key: "squats_50k", name: "Pilier de la Terre", emoji: "🏛️", description: "50 000 Squats cumulés", threshold: 50000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "SQUATS", type: "MILESTONE", condition: "Atteindre 50 000 squats cumulés." },
    { key: "squats_100k", name: "Atlas", emoji: "🌍", description: "100 000 Squats cumulés", threshold: 100000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "SQUATS", type: "MILESTONE", condition: "Atteindre 100 000 squats cumulés." },

    // Milestones (Tractions)
    { key: "pullups_1k", name: "Grimpette", emoji: "🧗", description: "1 000 Tractions cumulées", threshold: 1000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", condition: "Atteindre 1 000 tractions cumulées." },
    { key: "pullups_2k", name: "Alpiniste", emoji: "🏔️", description: "2 000 Tractions cumulées", threshold: 2000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", condition: "Atteindre 2 000 tractions cumulées." },
    { key: "pullups_3k", name: "Singe", emoji: "🐒", description: "3 000 Tractions cumulées", threshold: 3000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", condition: "Atteindre 3 000 tractions cumulées." },
    { key: "pullups_4k", name: "Gorille", emoji: "🦍", description: "4 000 Tractions cumulées", threshold: 4000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", condition: "Atteindre 4 000 tractions cumulées." },
    { key: "pullups_5k", name: "Tarzan", emoji: "🌴", description: "5 000 Tractions cumulées", threshold: 5000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", condition: "Atteindre 5 000 tractions cumulées." },
    { key: "pullups_10k", name: "Spiderman", emoji: "🕷️", description: "10 000 Tractions cumulées", threshold: 10000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", condition: "Atteindre 10 000 tractions cumulées." },
    { key: "pullups_20k", name: "Maître de la Gravité", emoji: "🛸", description: "20 000 Tractions cumulées", threshold: 20000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", condition: "Atteindre 20 000 tractions cumulées." },
    { key: "pullups_50k", name: "Lévitation", emoji: "🧞", description: "50 000 Tractions cumulées", threshold: 50000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", condition: "Atteindre 50 000 tractions cumulées." },

    // Milestones (Survivant)
    { key: "survivor_15d", name: "Promeneur", emoji: "🚶", description: "15 jours sans amende", threshold: 15, isUnique: false, isTransferable: false, metricType: "STREAK_NO_FINES", exerciseScope: "ALL", type: "MILESTONE", condition: "Enchaîner 15 jours consécutifs sans recevoir d'amende." },
    { key: "survivor_30d", name: "Le Survivant", emoji: "🛡️", description: "30 jours sans amende", threshold: 30, isUnique: false, isTransferable: false, metricType: "STREAK_NO_FINES", exerciseScope: "ALL", type: "MILESTONE", condition: "Enchaîner 30 jours consécutifs sans recevoir d'amende." },
    { key: "survivor_60d", name: "L'Intouchable", emoji: "👻", description: "60 jours sans amende", threshold: 60, isUnique: false, isTransferable: false, metricType: "STREAK_NO_FINES", exerciseScope: "ALL", type: "MILESTONE", condition: "Enchaîner 60 jours consécutifs sans recevoir d'amende." },
    { key: "survivor_90d", name: "Le Fantôme", emoji: "🥷", description: "90 jours sans amende", threshold: 90, isUnique: false, isTransferable: false, metricType: "STREAK_NO_FINES", exerciseScope: "ALL", type: "MILESTONE", condition: "Enchaîner 90 jours consécutifs sans recevoir d'amende." },
    { key: "survivor_120d", name: "Le Saint", emoji: "👼", description: "120 jours sans amende", threshold: 120, isUnique: false, isTransferable: false, metricType: "STREAK_NO_FINES", exerciseScope: "ALL", type: "MILESTONE", condition: "Enchaîner 120 jours consécutifs sans recevoir d'amende." },

    // Milestones (Amendes) - Mécène
    { key: "mecene_50", name: "Le Bon Samaritain", emoji: "😇", description: "50€ d'amendes payées", threshold: 50, isUnique: false, isTransferable: false, metricType: "FINES_AMOUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Payer un total de 50€ d'amendes pour soutenir la cagnotte." },
    { key: "mecene_100", name: "Sponsor Officiel", emoji: "💰", description: "100€ d'amendes payées", threshold: 100, isUnique: false, isTransferable: false, metricType: "FINES_AMOUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Payer un total de 100€ d'amendes pour soutenir la cagnotte." },

    // Milestones (Heures) - Lève-tôt (Avant 6h)
    { key: "early_bird_1", name: "Lève-tôt (1j)", emoji: "🌅", description: "Série avant 6h du matin", isUnique: false, isTransferable: false, metricType: "TIME_AWARD", threshold: 1, type: "MILESTONE", exerciseScope: "ALL", condition: "Réaliser au moins une série d'entraînement avant 6h00 du matin." },
    { key: "early_bird_3", name: "Lève-tôt (3j)", emoji: "🐓", description: "3 j. consécutifs avant 6h", isUnique: false, isTransferable: false, metricType: "TIME_AWARD", threshold: 3, type: "MILESTONE", exerciseScope: "ALL", condition: "Réaliser une série avant 6h00 pendant 3 jours consécutifs." },
    { key: "early_bird_7", name: "Lève-tôt (7j)", emoji: "☀️", description: "7 j. consécutifs avant 6h", isUnique: false, isTransferable: false, metricType: "TIME_AWARD", threshold: 7, type: "MILESTONE", exerciseScope: "ALL", condition: "Réaliser une série avant 6h00 pendant 7 jours consécutifs." },
    { key: "early_bird_30", name: "Lève-tôt (30j)", emoji: "🌞", description: "30 j. consécutifs avant 6h", isUnique: false, isTransferable: false, metricType: "TIME_AWARD", threshold: 30, type: "MILESTONE", exerciseScope: "ALL", condition: "Réaliser une série avant 6h00 pendant 30 jours consécutifs." },

    // Milestones (Heures) - Oiseau de Nuit (Après 22h)
    { key: "night_owl_1", name: "Oiseau de Nuit (1j)", emoji: "🦉", description: "Série après 22h", isUnique: false, isTransferable: false, metricType: "TIME_AWARD_LATE", threshold: 1, type: "MILESTONE", exerciseScope: "ALL", condition: "Réaliser au moins une série d'entraînement après 22h00." },
    { key: "night_owl_3", name: "Oiseau de Nuit (3j)", emoji: "🦇", description: "3 j. consécutifs après 22h", isUnique: false, isTransferable: false, metricType: "TIME_AWARD_LATE", threshold: 3, type: "MILESTONE", exerciseScope: "ALL", condition: "Réaliser une série après 22h00 pendant 3 jours consécutifs." },
    { key: "night_owl_7", name: "Oiseau de Nuit (7j)", emoji: "🌙", description: "7 j. consécutifs après 22h", isUnique: false, isTransferable: false, metricType: "TIME_AWARD_LATE", threshold: 7, type: "MILESTONE", exerciseScope: "ALL", condition: "Réaliser une série après 22h00 pendant 7 jours consécutifs." },
    { key: "night_owl_30", name: "Oiseau de Nuit (30j)", emoji: "🧛", description: "30 j. consécutifs après 22h", isUnique: false, isTransferable: false, metricType: "TIME_AWARD_LATE", threshold: 30, type: "MILESTONE", exerciseScope: "ALL", condition: "Réaliser une série après 22h00 pendant 30 jours consécutifs." },

    { key: "high_noon", name: "Midi Pile", emoji: "🕛", description: "Série à 12:00 pile", isUnique: false, isTransferable: false, metricType: "TIME_AWARD_EXACT", threshold: 1, type: "MILESTONE", exerciseScope: "ALL", condition: "Avoir la précision chirurgicale de valider une série à 12:00:00 exactement." },

    // Milestones (Heures) - Sprinter (Premier de la journée à atteindre la cible)
    { key: "sprinter_1", name: "Le Bip-Bip", emoji: "🏃", description: "Premier à valider sa cible journalière", threshold: 1, isUnique: false, isTransferable: false, metricType: "SPRINTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Être le tout premier utilisateur de la journée à atteindre son objectif complet." },
    { key: "sprinter_5", name: "Lièvre Rapide", emoji: "🐇", description: "5 fois premier à valider", threshold: 5, isUnique: false, isTransferable: false, metricType: "SPRINTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Être le premier à valider son objectif quotidien 5 jours différents." },
    { key: "sprinter_10", name: "Éclair", emoji: "⚡", description: "10 fois premier à valider", threshold: 10, isUnique: false, isTransferable: false, metricType: "SPRINTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Être le premier à valider son objectif quotidien 10 jours différents." },
    { key: "sprinter_30", name: "Sur Vitesse", emoji: "🏍️", description: "30 fois premier à valider", threshold: 30, isUnique: false, isTransferable: false, metricType: "SPRINTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Être le premier à valider son objectif quotidien 30 jours différents." },
    { key: "sprinter_50", name: "Fusée", emoji: "🚀", description: "50 fois premier à valider", threshold: 50, isUnique: false, isTransferable: false, metricType: "SPRINTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Être le premier à valider son objectif quotidien 50 jours différents." },
    { key: "sprinter_100", name: "Téléporté", emoji: "☄️", description: "100 fois premier à valider", threshold: 100, isUnique: false, isTransferable: false, metricType: "SPRINTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Être le premier à valider son objectif quotidien 100 jours différents." },

    // Seasonal / Events
    { key: "level_up", name: "Montée de Niveau", emoji: "⭐", description: "Est passé au niveau supérieur", isUnique: false, isTransferable: false, metricType: "LEVEL_UP", threshold: 0, type: "EVENT", exerciseScope: "ALL", condition: "Gagner assez d'XP pour progresser d'un niveau." },
    { key: "st_patrick", name: "La Saint-Patrick", emoji: "🍀", description: "S'être entraîné le 17 mars", isUnique: false, isTransferable: false, metricType: "DATE_AWARD_HARD", threshold: 17, type: "EVENT", exerciseScope: "ALL", condition: "Réaliser au moins une série le jour de la Saint-Patrick (17 mars)." },
    { key: "st_patrick_gold", name: "Saint-Patrick (Or)", emoji: "🏵️", description: "Avoir validé son objectif complet le 17 mars", isUnique: false, isTransferable: false, metricType: "DATE_AWARD_HARD_GOLD", threshold: 17, type: "EVENT", exerciseScope: "ALL", condition: "Atteindre son objectif complet le jour de la Saint-Patrick." },
    { key: "dday_hero", name: "Le Débarquement", emoji: "🎖️", description: "Avoir fait au moins une série le 06 juin", isUnique: false, isTransferable: false, metricType: "DATE_AWARD_HARD", threshold: 6, type: "EVENT", exerciseScope: "ALL", condition: "Réaliser au moins une série le jour du Débarquement (6 juin)." },
    { key: "easter_egg", name: "Pâques", emoji: "🥚", description: "Avoir fait au moins une série le jour de Pâques", isUnique: false, isTransferable: false, metricType: "DATE_AWARD_HARD", threshold: 0, type: "EVENT", exerciseScope: "ALL", condition: "Réaliser au moins une série le dimanche de Pâques." },
    { key: "st_marvin", name: "Saint Marvin", emoji: "🔥", description: "Avoir égalé ou battu EMBI le 08 Mars", isUnique: false, isTransferable: false, metricType: "MARVIN_AWARD", threshold: 8, type: "EVENT", exerciseScope: "ALL", condition: "Le 8 mars, égaler ou dépasser le volume de répétitions d'EMBI. Si EMBI finit 1er, il gagne 1500 XP." },
    { key: "st_damien", name: "Saint Damien", emoji: "⚔️", description: "Fêter la Saint Damien (18 Décembre)", isUnique: false, isTransferable: false, metricType: "DATE_AWARD", threshold: 18, type: "EVENT", exerciseScope: "ALL", condition: "Réaliser au moins une série le jour de la Saint-Damien (18 décembre)." },
    { key: "st_nicolas", name: "Saint Nicolas", emoji: "🍊", description: "Fêter la Saint Nicolas (06 Décembre)", isUnique: false, isTransferable: false, metricType: "DATE_AWARD", threshold: 6, type: "EVENT", exerciseScope: "ALL", condition: "Réaliser au moins une série le jour de la Saint-Nicolas (6 décembre)." },
    { key: "april_fools_1", name: "Mégalo-Carcharodon", emoji: "🦈", description: "Top 1 volume du 1er avril", isUnique: false, isTransferable: false, metricType: "APRIL_FOOLS_TIER", threshold: 1, exerciseScope: "ALL", type: "EVENT", condition: "Terminer à la 1ère place du classement de volume le 1er avril." },
    { key: "april_fools_2", name: "Gros Brochet", emoji: "🐊", description: "Top 2 volume du 1er avril", isUnique: false, isTransferable: false, metricType: "APRIL_FOOLS_TIER", threshold: 2, exerciseScope: "ALL", type: "EVENT", condition: "Terminer à la 2ème place du classement de volume le 1er avril." },
    { key: "april_fools_3", name: "Saumon Agile", emoji: "🎏", description: "Top 3 volume du 1er avril", isUnique: false, isTransferable: false, metricType: "APRIL_FOOLS_TIER", threshold: 3, exerciseScope: "ALL", type: "EVENT", condition: "Terminer à la 3ème place du classement de volume le 1er avril." },
    { key: "april_fools_4", name: "Truite Commune", emoji: "🐟", description: "Top 4 volume du 1er avril", isUnique: false, isTransferable: false, metricType: "APRIL_FOOLS_TIER", threshold: 4, exerciseScope: "ALL", type: "EVENT", condition: "Terminer à la 4ème place du classement de volume le 1er avril." },
    { key: "april_fools_5", name: "Petit Gardon", emoji: "🐡", description: "Top 5 volume du 1er avril", isUnique: false, isTransferable: false, metricType: "APRIL_FOOLS_TIER", threshold: 5, exerciseScope: "ALL", type: "EVENT", condition: "Terminer à la 5ème place du classement de volume le 1er avril." },
    { key: "april_fools_6", name: "Minuscule Sardine", emoji: "🐠", description: "Top 6 (ou pire) du 1er avril", isUnique: false, isTransferable: false, metricType: "APRIL_FOOLS_TIER", threshold: 6, exerciseScope: "ALL", type: "EVENT", condition: "S'être entraîné le 1er avril (hors top 5)." },
    { key: "level_down", name: "Rétrogradation", emoji: "🚨", description: "Est redescendu d'un niveau", isUnique: false, isTransferable: false, metricType: "LEVEL_DOWN", threshold: 0, type: "EVENT", exerciseScope: "ALL", condition: "Perdre assez d'XP (généralement par vol de badge) pour redescendre d'un niveau." },
];
