export type BadgeRarity = 'COMMON' | 'RARE' | 'EPIC' | 'LEGENDARY';

export interface BadgeDefinition {
    key: string;
    name: string;
    emoji: string;
    description: string;
    metricType: string;
    exerciseScope: string;
    type: string;
    condition: string;
    rarity: BadgeRarity;
    threshold?: number;
    seriesTarget?: number;
    isUnique?: boolean;
    isTransferable?: boolean;
}

export const BADGE_DEFINITIONS: BadgeDefinition[] = [
    // B1: Competitive Transferable (COMMON - Frequent Rotation)
    { key: "big_flexer", name: "Gros Flexeur", emoji: "🚀", rarity: "COMMON", description: "Meilleur bonus reps (Total - Cible) sur une journée", metricType: "MAX_BONUS", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Obtenir le plus gros surplus de répétitions par rapport à l'objectif sur une journée." },
    { key: "regular_flexer", name: "Flexeur Régulier", emoji: "🔥", rarity: "COMMON", description: "Plus longue streak de jours avec bonus > 0", metricType: "BONUS_STREAK", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Maintenir la plus longue série de jours consécutifs avec un surplus de répétitions." },
    { key: "perfect_soldier", name: "Le bon petit nazi", emoji: "👨🏻", rarity: "COMMON", description: "Celui qui fait exactement le bon nombre de reps chaque jour. Tie-break: plus longue streak.", metricType: "PERFECT_TARGET_STREAK", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Atteindre exactement l'objectif quotidien, sans une répétition de plus ni de moins." },
    { key: "king_of_set_all", name: "Roi de la Plus Longue Série", emoji: "👑", rarity: "COMMON", description: "Plus grande série réalisée (tous exos)", metricType: "MAX_SET", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Réaliser la plus grande série de répétitions ininterrompue, tous exercices confondus." },
    { key: "king_of_set_pushups", name: "Furie des Pompes", emoji: "💪", rarity: "COMMON", description: "Plus grande série de pompes", metricType: "MAX_SET", exerciseScope: "PUSHUPS", type: "COMPETITIVE", condition: "Réaliser la plus grande série de pompes ininterrompue." },
    { key: "king_of_set_pullups", name: "Roi des Tractions", emoji: "🧗", rarity: "COMMON", description: "Plus grande série de tractions", metricType: "MAX_SET", exerciseScope: "PULLUPS", type: "COMPETITIVE", condition: "Réaliser la plus grande série de tractions strictes." },
    { key: "king_of_set_squats", name: "Empereur des Squats", emoji: "🦾", rarity: "COMMON", description: "Plus grande série de squats", metricType: "MAX_SET", exerciseScope: "SQUATS", type: "COMPETITIVE", condition: "Réaliser la plus grande série de squats ininterrompue." },
    { key: "master_thief", name: "Meilleur Voleur", emoji: "🦝", rarity: "COMMON", description: "Celui qui a volé le plus de badges aux autres", metricType: "STEAL_COUNT", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Dérober le plus grand nombre de badges compétitifs aux autres membres." },
    { key: "yin_yang", name: "Le Yin et le Yang", emoji: "☯️", rarity: "COMMON", description: "Équilibre Pompes/Squats le plus proche de 100% (500 reps mini cumulées)", metricType: "BALANCE_RATIO", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Avoir le ratio le plus équilibré entre les pompes et les squats (min. 500 reps cumulées)." },
    { key: "mono_maniac", name: "Le Mono-Maniaque", emoji: "🎯", rarity: "COMMON", description: "Plus longue streak d'un seul exercice par jour", metricType: "MONO_EXO_STREAK", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Chaque jour, ne pratiquer qu'un seul type d'exercice pendant la plus longue période." },
    { key: "trinity", name: "La Trinité", emoji: "🔺", rarity: "COMMON", description: "Plus longue streak avec au moins 30% Pompes, 30% Tractions, 30% Squats par jour", metricType: "TRI_EXO_STREAK", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Répartir ses efforts : au moins 30% de chaque exercice chaque jour." },
    { key: "trinity_gold", name: "Trinité d'Or", emoji: "🔱", rarity: "EPIC", description: "Fait 3x le nombre de reps du jour (min 1 rep de chaque exo)", metricType: "TRINITY_GOLD", exerciseScope: "ALL", type: "MILESTONE", condition: "Sur une journée, valider 3 fois l'objectif cumulé avec au moins 1 répétition de chaque type d'exercice." },
    { key: "trinity_ultimate", name: "Trinité Ultime", emoji: "🔱✨", rarity: "LEGENDARY", description: "Fait l'objectif total sur CHAQUE exercice le même jour", metricType: "TRINITY_ULTIMATE", exerciseScope: "ALL", type: "MILESTONE", condition: "Sur une journée, valider l'intégralité de l'objectif quotidien séparément sur les pompes, les tractions ET les squats." },
    { key: "mecene_year", name: "Mécène de l'Année", emoji: "💸", rarity: "COMMON", description: "Plus grand donneur à la cagnotte (amendes payées)", metricType: "TOTAL_FINES_AMOUNT", exerciseScope: "ALL", type: "COMPETITIVE", condition: "Avoir payé le plus grand montant d'amendes cumulées." },

    // B2: Series Counts (Competitive - COMMON)
    { key: "series_pushups_10", name: "Roi des Séries de 10", emoji: "🧱", rarity: "COMMON", description: "Plus grand nombre de séries de 10 pompes", seriesTarget: 10, metricType: "SERIES_COUNT", exerciseScope: "PUSHUPS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 10 pompes exactement." },
    { key: "series_pushups_20", name: "Roi des Séries de 20", emoji: "🧱", rarity: "COMMON", description: "Plus grand nombre de séries de 20 pompes", seriesTarget: 20, metricType: "SERIES_COUNT", exerciseScope: "PUSHUPS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 20 pompes exactement." },
    { key: "series_pushups_30", name: "Roi des Séries de 30", emoji: "🧱", rarity: "COMMON", description: "Plus grand nombre de séries de 30 pompes", seriesTarget: 30, metricType: "SERIES_COUNT", exerciseScope: "PUSHUPS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 30 pompes exactement." },
    { key: "series_pullups_10", name: "Roi des Séries de 10 Tractions", emoji: "🧗", rarity: "COMMON", description: "Plus grand nombre de séries de 10 tractions", seriesTarget: 10, metricType: "SERIES_COUNT", exerciseScope: "PULLUPS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 10 tractions exactement." },
    { key: "series_squats_20", name: "Roi des Séries de 20 Squats", emoji: "🦵", rarity: "COMMON", description: "Plus grand nombre de séries de 20 squats", seriesTarget: 20, metricType: "SERIES_COUNT", exerciseScope: "SQUATS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 20 squats exactement." },
    { key: "series_squats_50", name: "Roi des Séries de 50 Squats", emoji: "🦵", rarity: "COMMON", description: "Plus grand nombre de séries de 50 squats", seriesTarget: 50, metricType: "SERIES_COUNT", exerciseScope: "SQUATS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 50 squats exactement." },
    { key: "series_squats_100", name: "Roi des Séries de 100 Squats", emoji: "🦵", rarity: "COMMON", description: "Plus grand nombre de séries de 100 squats", seriesTarget: 100, metricType: "SERIES_COUNT", exerciseScope: "SQUATS", type: "COMPETITIVE", condition: "Réaliser le plus de séries de 100 squats exactement." },

    // B3: Unique Achievement (LEGENDARY)
    { key: "unique_pushups_50", name: "Premier 50 Pompes", emoji: "🥈", rarity: "LEGENDARY", description: "Premier utilisateur à réaliser 50 pompes d'un coup", threshold: 50, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PUSHUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 50 pompes ininterrompues." },
    { key: "unique_pushups_80", name: "Premier 80 Pompes", emoji: "🥇", rarity: "LEGENDARY", description: "Premier utilisateur à réaliser 80 pompes d'un coup", threshold: 80, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PUSHUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 80 pompes ininterrompues." },
    { key: "unique_pushups_100", name: "Premier 100 Pompes", emoji: "👑", rarity: "LEGENDARY", description: "Premier utilisateur à réaliser 100 pompes d'un coup", threshold: 100, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PUSHUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 100 pompes ininterrompues." },
    { key: "legendary_pullups_20", name: "Premier 20 Tractions", emoji: "💎", rarity: "LEGENDARY", description: "Premier utilisateur à réaliser 20 tractions strictes", threshold: 20, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PULLUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 20 tractions strictes." },
    { key: "legendary_pullups_30", name: "Premier 30 Tractions", emoji: "☄️", rarity: "LEGENDARY", description: "Premier utilisateur à réaliser 30 tractions strictes", threshold: 30, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "PULLUPS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 30 tractions strictes." },
    { key: "legendary_squats_150", name: "Premier 150 Squats", emoji: "🦵", rarity: "LEGENDARY", description: "Premier utilisateur à réaliser 150 squats sans break", threshold: 150, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "SQUATS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 150 squats ininterrompus." },
    { key: "legendary_squats_300", name: "Premier 300 Squats", emoji: "🏋️", rarity: "LEGENDARY", description: "Premier utilisateur à réaliser 300 squats sans break", threshold: 300, isUnique: true, isTransferable: false, metricType: "FIRST_REACH", exerciseScope: "SQUATS", type: "LEGENDARY", condition: "Être le tout premier de l'histoire de l'app à valider 300 squats ininterrompus." },

    // Headhunter Badges (RARE to EPIC)
    { key: "headhunter_1", name: "Chasseur Novice", emoji: "🎯", rarity: "RARE", description: "A décroché 1 badge à l'honneur", threshold: 1, metricType: "HEADHUNTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Décrocher son tout premier badge mis à l'honneur." },
    { key: "headhunter_3", name: "Chasseur de têtes", emoji: "🏹", rarity: "RARE", description: "A décroché 3 badges à l'honneur", threshold: 3, metricType: "HEADHUNTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Décrocher 3 badges mis à l'honneur." },
    { key: "headhunter_10", name: "Traqueur d'Elite", emoji: "👤", rarity: "EPIC", description: "A décroché 10 badges à l'honneur", threshold: 10, metricType: "HEADHUNTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Décrocher 10 badges mis à l'honneur." },
    { key: "headhunter_50", name: "Légende de la Chasse", emoji: "💀", rarity: "EPIC", description: "A décroché 50 badges à l'honneur", threshold: 50, metricType: "HEADHUNTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Décrocher 50 badges mis à l'honneur." },
    { key: "headhunter_100", name: "Prédateur Absolu", emoji: "👹", rarity: "LEGENDARY", description: "A décroché 100 badges à l'honneur", threshold: 100, metricType: "HEADHUNTER_COUNT", exerciseScope: "ALL", type: "MILESTONE", condition: "Décrocher 100 badges mis à l'honneur." },

    // B4: Milestones (RARE)
    { key: "centurion", name: "Le Centurion", emoji: "💯", rarity: "RARE", description: "Avoir fait 100 reps d'un coup", threshold: 100, isUnique: false, isTransferable: false, metricType: "MILESTONE_SET", exerciseScope: "ALL", type: "MILESTONE", condition: "Réaliser une série de 100 répétitions ou plus (tous exercices)." },
    { key: "general_1k", name: "Le Soldat", emoji: "🔫", rarity: "RARE", description: "1 000 reps cumulées", threshold: 1000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 1 000 répétitions cumulées au total." },
    { key: "general_5k", name: "Le Sergent", emoji: "🛡️", rarity: "RARE", description: "5 000 reps cumulées", threshold: 5000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 5 000 répétitions cumulées au total." },
    { key: "general_10k", name: "Le Général", emoji: "🏰", rarity: "RARE", description: "10 000 reps cumulées", threshold: 10000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 10 000 répétitions cumulées au total." },
    { key: "general_20k", name: "Le Warlord", emoji: "⚔️", rarity: "EPIC", description: "20 000 reps cumulées", threshold: 20000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 20 000 répétitions cumulées au total." },
    { key: "general_40k", name: "Le Conquérant", emoji: "🌍", rarity: "EPIC", description: "40 000 reps cumulées", threshold: 40000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 40 000 répétitions cumulées au total." },
    { key: "general_60k", name: "Le Demi-Dieu", emoji: "⚡", rarity: "LEGENDARY", description: "60 000 reps cumulées", threshold: 60000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 60 000 répétitions cumulées au total." },
    { key: "general_100k", name: "L'Immortel", emoji: "🌌", rarity: "LEGENDARY", description: "100 000 reps cumulées", threshold: 100000, isUnique: false, isTransferable: false, metricType: "MILESTONE_TOTAL", exerciseScope: "ALL", type: "MILESTONE", condition: "Atteindre 100 000 répétitions cumulées au total." },

    // Exercise Specific Milestones (RARE)
    { key: "pushups_1k", name: "Pousseur Novice", emoji: "🥉", rarity: "RARE", threshold: 1000, metricType: "MILESTONE_TOTAL", exerciseScope: "PUSHUPS", type: "MILESTONE", description: "1 000 Pompes cumulées", condition: "Atteindre 1 000 pompes cumulées." },
    { key: "pushups_10k", name: "Pousseur Expert", emoji: "🥈", rarity: "RARE", threshold: 10000, metricType: "MILESTONE_TOTAL", exerciseScope: "PUSHUPS", type: "MILESTONE", description: "10 000 Pompes cumulées", condition: "Atteindre 10 000 pompes cumulées." },
    { key: "pushups_50k", name: "Dieu des Pompes", emoji: "🥇", rarity: "EPIC", threshold: 50000, metricType: "MILESTONE_TOTAL", exerciseScope: "PUSHUPS", type: "MILESTONE", description: "50 000 Pompes cumulées", condition: "Atteindre 50 000 pompes cumulées." },
    { key: "squats_1k", name: "Cuisses de Poulet", emoji: "🍗", rarity: "RARE", threshold: 1000, metricType: "MILESTONE_TOTAL", exerciseScope: "SQUATS", type: "MILESTONE", description: "1 000 Squats cumulés", condition: "Atteindre 1 000 squats cumulés." },
    { key: "squats_10k", name: "Cuisses d'Acier", emoji: "🦾", rarity: "RARE", threshold: 10000, metricType: "MILESTONE_TOTAL", exerciseScope: "SQUATS", type: "MILESTONE", description: "10 000 Squats cumulés", condition: "Atteindre 10 000 squats cumulés." },
    { key: "squats_50k", name: "Pilier de la Terre", emoji: "🏛️", rarity: "EPIC", threshold: 50000, metricType: "MILESTONE_TOTAL", exerciseScope: "SQUATS", type: "MILESTONE", description: "50 000 Squats cumulés", condition: "Atteindre 50 000 squats cumulés." },
    { key: "squats_100k", name: "Atlas", emoji: "🌍", rarity: "LEGENDARY", threshold: 100000, metricType: "MILESTONE_TOTAL", exerciseScope: "SQUATS", type: "MILESTONE", description: "100 000 Squats cumulés", condition: "Atteindre 100 000 squats cumulés." },
    { key: "pullups_1k", name: "Grimpette", emoji: "🧗", rarity: "RARE", threshold: 1000, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", description: "1 000 Tractions cumulées", condition: "Atteindre 1 000 tractions cumulées." },
    { key: "pullups_5k", name: "Tarzan", emoji: "🌴", rarity: "RARE", threshold: 5000, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", description: "5 000 Tractions cumulées", condition: "Atteindre 5 000 tractions cumulées." },
    { key: "pullups_10k", name: "Spiderman", emoji: "🕷️", rarity: "EPIC", threshold: 10000, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", description: "10 000 Tractions cumulées", condition: "Atteindre 10 000 tractions cumulées." },
    { key: "pullups_50k", name: "Lévitation", emoji: "🧞", rarity: "LEGENDARY", threshold: 50000, metricType: "MILESTONE_TOTAL", exerciseScope: "PULLUPS", type: "MILESTONE", description: "50 000 Tractions cumulées", condition: "Atteindre 50 000 tractions cumulées." },

    // Time Awards & Streaks (RARE)
    { key: "survivor_30d", name: "Le Survivant", emoji: "🛡️", rarity: "RARE", threshold: 30, metricType: "STREAK_NO_FINES", type: "MILESTONE", exerciseScope: "ALL", description: "30 jours sans amende", condition: "Enchaîner 30 jours consécutifs sans recevoir d'amende." },
    { key: "survivor_90d", name: "Le Fantôme", emoji: "🥷", rarity: "EPIC", threshold: 90, metricType: "STREAK_NO_FINES", type: "MILESTONE", exerciseScope: "ALL", description: "90 jours sans amende", condition: "Enchaîner 90 jours consécutifs sans recevoir d'amende." },
    { key: "early_bird_7", name: "Lève-tôt (7j)", emoji: "☀️", rarity: "RARE", threshold: 7, metricType: "TIME_AWARD", type: "MILESTONE", exerciseScope: "ALL", description: "7 j. consécutifs avant 6h", condition: "Réaliser une série avant 6h00 pendant 7 jours consécutifs." },
    { key: "night_owl_7", name: "Oiseau de Nuit (7j)", emoji: "🌙", rarity: "RARE", threshold: 7, metricType: "TIME_AWARD_LATE", type: "MILESTONE", exerciseScope: "ALL", description: "7 j. consécutifs après 22h", condition: "Réaliser une série après 22h00 pendant 7 jours consécutifs." },
    { key: "sprinter_10", name: "Éclair", emoji: "⚡", rarity: "RARE", threshold: 10, metricType: "SPRINTER_COUNT", type: "MILESTONE", exerciseScope: "ALL", description: "10 fois premier à valider", condition: "Être le premier à valider son objectif quotidien 10 jours différents." },

    // Special Events (EPIC)
    { key: "level_up", name: "Montée de Niveau", emoji: "⭐", rarity: "RARE", metricType: "LEVEL_UP", type: "EVENT", exerciseScope: "ALL", description: "Est passé au niveau supérieur", condition: "Gagner assez d'XP pour progresser d'un niveau." },
    { key: "st_patrick", name: "Trèfle de Chance", emoji: "🍀", rarity: "EPIC", metricType: "DATE_AWARD_HARD", type: "EVENT", exerciseScope: "ALL", description: "S'être entraîné le 17 mars", condition: "Réaliser au moins une série le jour de la Saint-Patrick (17 mars)." },
    { key: "st_patrick_gold", name: "Trèfle d'Or", emoji: "☘️", rarity: "LEGENDARY", metricType: "DATE_AWARD_HARD_GOLD", type: "EVENT", exerciseScope: "ALL", description: "Quota total validé le 17 mars", condition: "Atteindre le quota total du jour le jour de la Saint-Patrick." },
    { key: "st_marvin", name: "Saint Marvin", emoji: "🔥", rarity: "EPIC", metricType: "MARVIN_AWARD", type: "EVENT", exerciseScope: "ALL", description: "Avoir égalé ou battu EMBI le 08 Mars", condition: "Le 8 mars, égaler ou dépasser le volume de répétitions d'EMBI." },
    { key: "april_fools_1", name: "Mégalo-Carcharodon", emoji: "🦈", rarity: "EPIC", metricType: "APRIL_FOOLS_TIER", type: "EVENT", exerciseScope: "ALL", description: "Top 1 volume du 1er avril", condition: "Terminer à la 1ère place du classement de volume le 1er avril." },
    { key: "st_patrick_diamond", name: "Trèfle de Diamant", emoji: "💎", rarity: "LEGENDARY", metricType: "DATE_COMPETITIVE_REPS", type: "COMPETITIVE", exerciseScope: "ALL", description: "Le plus gros volume du 17 mars", condition: "Terminer à la 1ère place du classement de volume le jour de la Saint-Patrick." },
    { key: "st_patrick_pushups", name: "Trèfle d'Émeraude", emoji: "💚", rarity: "EPIC", metricType: "DATE_COMPETITIVE_SET_PUSHUPS", type: "COMPETITIVE", exerciseScope: "PUSHUPS", description: "Plus grosse série de pompes le 17 mars", condition: "Réaliser la plus grosse série de pompes le jour de la Saint-Patrick." },
    { key: "st_patrick_pullups", name: "Trèfle de Saphir", emoji: "💙", rarity: "EPIC", metricType: "DATE_COMPETITIVE_SET_PULLUPS", type: "COMPETITIVE", exerciseScope: "PULLUPS", description: "Plus grosse série de tractions le 17 mars", condition: "Réaliser la plus grosse série de tractions le jour de la Saint-Patrick." },
    { key: "st_patrick_squats", name: "Trèfle de Rubis", emoji: "❤️", rarity: "EPIC", metricType: "DATE_COMPETITIVE_SET_SQUATS", type: "COMPETITIVE", exerciseScope: "SQUATS", description: "Plus grosse série de squats le 17 mars", condition: "Réaliser la plus grosse série de squats le jour de la Saint-Patrick." },

    // Monthly Competitive (EPIC)
    { key: "month_top_volume", name: "Seigneur du Mois", emoji: "🏛️", rarity: "EPIC", metricType: "MONTH_TOP_VOLUME", type: "COMPETITIVE", exerciseScope: "ALL", description: "Plus gros volume total du mois", condition: "Terminer à la 1ère place du classement de volume cumulé sur le mois en cours." },
    { key: "month_top_pushups_set", name: "Bras d'Acier du Mois", emoji: "🦾", rarity: "EPIC", metricType: "MONTH_TOP_SET", type: "COMPETITIVE", exerciseScope: "PUSHUPS", description: "Plus grosse série de pompes du mois", condition: "Réaliser la plus grosse série de pompes ininterrompue au cours du mois." },
    { key: "month_top_pullups_set", name: "Grimpeur du Mois", emoji: "🧗", rarity: "EPIC", metricType: "MONTH_TOP_SET", type: "COMPETITIVE", exerciseScope: "PULLUPS", description: "Plus grosse série de tractions du mois", condition: "Réaliser la plus grosse série de tractions ininterrompue au cours du mois." },
    { key: "month_top_squats_set", name: "Pilier du Mois", emoji: "🏛️", rarity: "EPIC", metricType: "MONTH_TOP_SET", type: "COMPETITIVE", exerciseScope: "SQUATS", description: "Plus grosse série de squats du mois", condition: "Réaliser la plus grosse série de squats ininterrompue au cours du mois." },
    { key: "month_total_pushups", name: "Forçat des Pompes", emoji: "🛠️", rarity: "RARE", metricType: "MONTH_TOTAL_EXO", type: "COMPETITIVE", exerciseScope: "PUSHUPS", description: "Volume de pompes le plus élevé du mois", condition: "Cumuler le plus de répétitions en pompes au cours du mois." },
    { key: "month_total_pullups", name: "Traqueur du Mois", emoji: "🏹", rarity: "RARE", metricType: "MONTH_TOTAL_EXO", type: "COMPETITIVE", exerciseScope: "PULLUPS", description: "Volume de tractions le plus élevé du mois", condition: "Cumuler le plus de répétitions en tractions au cours du mois." },
    { key: "month_total_squats", name: "Porteur du Mois", emoji: "🪵", rarity: "RARE", metricType: "MONTH_TOTAL_EXO", type: "COMPETITIVE", exerciseScope: "SQUATS", description: "Volume de squats le plus élevé du mois", condition: "Cumuler le plus de répétitions en squats au cours du mois." },
];
